FROM nginxinc/nginx-unprivileged:stable-alpine
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY ./src/ /usr/share/nginx/html
COPY ./config/config.production.js /usr/share/nginx/html/config.js

CMD ["nginx", "-g", "daemon off;"]
