version: "3.8"

networks:
  default:
    name: typingrealm
    external: true

services:
  typingrealm-caddy:
    image: caddy
    container_name: typingrealm-caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /data/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /data/caddy/data:/data
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m

  typingrealm-pgadmin:
    image: dpage/pgadmin4
    container_name: typingrealm-pgadmin
    volumes:
      - /data/pgadmin/data:/var/lib/pgadmin
    env_file:
      - /data/pgadmin/secrets.env
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
