version: "3.8"

networks:
  default:
    name: typingrealm

services:
  typingrealm-web-ui:
    image: ${DOCKER_REGISTRY-}typingrealm-web-ui
    container_name: typingrealm-web-ui
    build:
      context: frontend/.
      dockerfile: Dockerfile-production
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m

  typingrealm-caddy:
    image: caddy
    container_name: typingrealm-caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./infrastructure-data/prod/caddy_data:/data
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m

  typingrealm-typing-1:
    image: ${DOCKER_REGISTRY-}typingrealm-typing
    container_name: typingrealm-typing-1
    build:
      context: backend/.
      dockerfile: TypingRealm.Typing.Api/Dockerfile-production
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - .env.production.typing
      - secrets.env

  typingrealm-typing-2:
    image: ${DOCKER_REGISTRY-}typingrealm-typing
    container_name: typingrealm-typing-2
    build:
      context: backend/.
      dockerfile: TypingRealm.Typing.Api/Dockerfile-production
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - .env.production.typing
      - secrets.env

  typingrealm-typing-postgres:
    image: postgres
    container_name: typingrealm-typing-postgres
    ports:
      - 10132:5432 # Port shouldn't be exposed in production.
    volumes:
      - ./infrastructure-data/prod/typing/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - .env.production.typing
