version: "3.8"

networks:
  default:
    name: typingrealm
    external: true

services:
  typingrealm-web:
    image: ghcr.io/ewancoder/typingrealm-web:main
    container_name: typingrealm-web
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m

  typingrealm-game-web:
    image: ghcr.io/ewancoder/typingrealm-game-web:main
    container_name: typingrealm-game-web
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m

  typingrealm-typing-1:
    image: ghcr.io/ewancoder/typingrealm-typing-api:main
    container_name: typingrealm-typing-1
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - /data/typingrealm/prod/typing/.env
      - /data/typingrealm/prod/typing/secrets.env

  typingrealm-typing-2:
    image: ghcr.io/ewancoder/typingrealm-typing-api:main
    container_name: typingrealm-typing-2
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - /data/typingrealm/prod/typing/.env
      - /data/typingrealm/prod/typing/secrets.env

  typingrealm-typing-postgres:
    image: postgres:16
    container_name: typingrealm-typing-postgres
    ports:
      - 10132:5432 # Port shouldn't be exposed in production.
    volumes:
      - /data/typingrealm/prod/typing/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    mem_limit: 1g
    mem_reservation: 750m
    env_file:
      - /data/typingrealm/prod/typing/.env
