# TODO: Do not copy dockerfiles, just use environment variable.

FROM node:latest AS build
WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install -g @angular/cli
RUN npm install

COPY . .
#COPY src/config.development.ts src/config.ts
RUN npm run build --prod

FROM nginxinc/nginx-unprivileged:stable-alpine
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/src/app/dist/typingrealm/browser /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
